//! In-module codegen tests: these call the private generation functions directly
//! (the Go/C generator in-lib test style) and assert on the emitted Zig substrings.

use super::*;
use csilgen_common::{
    CsilGroupKey, CsilPosition, CsilRule, CsilServiceOperation, CsilSpecSerialized,
    GeneratorConfig, GeneratorMetadata,
};

fn pos() -> CsilPosition {
    CsilPosition {
        line: 1,
        column: 1,
        offset: 0,
    }
}

fn metadata() -> GeneratorMetadata {
    GeneratorMetadata {
        name: "zig-generator".to_string(),
        version: "0.1.0".to_string(),
        description: String::new(),
        target: "zig".to_string(),
        capabilities: vec![],
        author: None,
        homepage: None,
    }
}

fn builtin(name: &str) -> CsilTypeExpression {
    CsilTypeExpression::Builtin(name.to_string())
}

fn bare_entry(name: &str, value_type: CsilTypeExpression) -> CsilGroupEntry {
    CsilGroupEntry {
        key: Some(CsilGroupKey::Bare(name.to_string())),
        value_type,
        occurrence: None,
        metadata: vec![],
        doc_comments: vec![],
    }
}

fn input_with_rules(
    rules: Vec<CsilRule>,
    target: &str,
    options: HashMap<String, serde_json::Value>,
) -> WasmGeneratorInput {
    let service_count = rules
        .iter()
        .filter(|r| matches!(r.rule_type, CsilRuleType::ServiceDef(_)))
        .count();
    WasmGeneratorInput {
        csil_spec: CsilSpecSerialized {
            rules,
            source_content: None,
            service_count,
            fields_with_metadata_count: 0,
        },
        config: GeneratorConfig {
            target: target.to_string(),
            output_dir: "/tmp".to_string(),
            options,
        },
        generator_metadata: metadata(),
    }
}

fn group_rule(name: &str, entries: Vec<CsilGroupEntry>) -> CsilRule {
    CsilRule {
        name: name.to_string(),
        rule_type: CsilRuleType::GroupDef(CsilGroupExpression { entries }),
        position: pos(),
        doc_comments: vec![],
    }
}

fn op(
    name: &str,
    input: CsilTypeExpression,
    output: CsilTypeExpression,
    direction: CsilServiceDirection,
    wire_id: Option<u64>,
) -> CsilServiceOperation {
    CsilServiceOperation {
        name: name.to_string(),
        input_type: input,
        output_type: output,
        direction,
        position: pos(),
        doc_comments: vec![],
        wire_id,
    }
}

fn service_rule(
    name: &str,
    operations: Vec<CsilServiceOperation>,
    wire_id: Option<u64>,
) -> CsilRule {
    CsilRule {
        name: name.to_string(),
        rule_type: CsilRuleType::ServiceDef(CsilServiceDefinition {
            operations,
            wire_id,
        }),
        position: pos(),
        doc_comments: vec![],
    }
}

#[test]
fn basic_struct_emits_struct_and_fields() {
    let input = input_with_rules(
        vec![group_rule(
            "User",
            vec![
                bare_entry("name", builtin("text")),
                bare_entry("issued_at", builtin("uint")),
            ],
        )],
        "zig",
        HashMap::new(),
    );
    let config = ZigConfig::from_options(&input.config.options).unwrap();
    let types = generate_types(&input, &config).expect("types emitted");
    assert!(types.contains("pub const User = struct {"));
    // snake_case field names map verbatim (wire keys stay verbatim).
    assert!(types.contains("name: []const u8,"));
    assert!(types.contains("issued_at: u64,"));
    assert!(types.contains("Code generated by csilgen; DO NOT EDIT."));
}

#[test]
fn optional_scalar_becomes_optional_with_default() {
    let mut entry = bare_entry("count", builtin("uint"));
    entry.occurrence = Some(CsilOccurrence::Optional);
    let input = input_with_rules(vec![group_rule("Bag", vec![entry])], "zig", HashMap::new());
    let config = ZigConfig::from_options(&input.config.options).unwrap();
    let types = generate_types(&input, &config).unwrap();
    assert!(types.contains("count: ?u64 = null,"));
}

#[test]
fn array_field_becomes_slice() {
    let entry = bare_entry(
        "tags",
        CsilTypeExpression::Array {
            element_type: Box::new(builtin("text")),
            occurrence: None,
        },
    );
    let input = input_with_rules(vec![group_rule("Post", vec![entry])], "zig", HashMap::new());
    let config = ZigConfig::from_options(&input.config.options).unwrap();
    let types = generate_types(&input, &config).unwrap();
    assert!(types.contains("tags: [][]const u8,"));
}

#[test]
fn map_field_becomes_hashmap_and_imports_std() {
    let entry = bare_entry(
        "labels",
        CsilTypeExpression::Map {
            key: Box::new(builtin("text")),
            value: Box::new(builtin("int")),
            occurrence: None,
        },
    );
    let input = input_with_rules(vec![group_rule("Doc", vec![entry])], "zig", HashMap::new());
    let config = ZigConfig::from_options(&input.config.options).unwrap();
    let types = generate_types(&input, &config).unwrap();
    assert!(types.contains("const std = @import(\"std\");"));
    assert!(types.contains("labels: std.StringHashMapUnmanaged(i64),"));
}

#[test]
fn bytes_decimal_timestamp_map_to_types_and_imports() {
    let input = input_with_rules(
        vec![group_rule(
            "Rec",
            vec![
                bare_entry("blob", builtin("bytes")),
                bare_entry("amount", builtin("decimal")),
                bare_entry("when", builtin("timestamp")),
            ],
        )],
        "zig",
        HashMap::new(),
    );
    let config = ZigConfig::from_options(&input.config.options).unwrap();
    let types = generate_types(&input, &config).unwrap();
    assert!(types.contains("blob: []const u8,"));
    assert!(types.contains("amount: CsilDecimal,"));
    assert!(types.contains("when: CsilTimestamp,"));
    assert!(types.contains("@import(\"csil_decimal.gen.zig\").CsilDecimal"));
    assert!(types.contains("@import(\"csil_timestamp.gen.zig\").CsilTimestamp"));
}

#[test]
fn decimal_helper_file_emitted_only_under_csil_mapping() {
    let rules = vec![group_rule(
        "Rec",
        vec![bare_entry("amount", builtin("decimal"))],
    )];
    let csil = process_generation(input_with_rules(rules.clone(), "zig", HashMap::new())).unwrap();
    assert!(csil.files.iter().any(|f| f.path == "csil_decimal.gen.zig"));

    let mut opts = HashMap::new();
    opts.insert("decimal_mapping".to_string(), serde_json::json!("library"));
    let lib = process_generation(input_with_rules(rules, "zig", opts)).unwrap();
    assert!(!lib.files.iter().any(|f| f.path == "csil_decimal.gen.zig"));
}

#[test]
fn type_alias_emitted() {
    let rule = CsilRule {
        name: "UserId".to_string(),
        rule_type: CsilRuleType::TypeDef(builtin("uint")),
        position: pos(),
        doc_comments: vec![],
    };
    let input = input_with_rules(vec![rule], "zig", HashMap::new());
    let config = ZigConfig::from_options(&input.config.options).unwrap();
    let types = generate_types(&input, &config).unwrap();
    assert!(types.contains("pub const UserId = u64;"));
}

#[test]
fn text_literal_choice_is_an_enum_with_wire_names() {
    let rule = CsilRule {
        name: "Color".to_string(),
        rule_type: CsilRuleType::TypeChoice(vec![
            CsilTypeExpression::Literal(CsilLiteralValue::Text("red".to_string())),
            CsilTypeExpression::Literal(CsilLiteralValue::Text("dark-green".to_string())),
        ]),
        position: pos(),
        doc_comments: vec![],
    };
    let input = input_with_rules(vec![rule], "zig", HashMap::new());
    let config = ZigConfig::from_options(&input.config.options).unwrap();
    let types = generate_types(&input, &config).unwrap();
    assert!(types.contains("pub const Color = enum {"));
    assert!(types.contains("    red,"));
    // kebab literal -> snake_case Zig tag, but the wire form stays verbatim.
    assert!(types.contains("    dark_green,"));
    assert!(types.contains(".dark_green => \"dark-green\","));
    assert!(types.contains("pub fn wire_name(self: Color) []const u8"));
}

#[test]
fn reference_choice_is_a_tagged_union_with_variant_names() {
    let rule = CsilRule {
        name: "DepositResult".to_string(),
        rule_type: CsilRuleType::TypeChoice(vec![
            CsilTypeExpression::Reference("ClaimResponse".to_string()),
            CsilTypeExpression::Reference("ServiceError".to_string()),
        ]),
        position: pos(),
        doc_comments: vec![],
    };
    let input = input_with_rules(vec![rule], "zig", HashMap::new());
    let config = ZigConfig::from_options(&input.config.options).unwrap();
    let types = generate_types(&input, &config).unwrap();
    assert!(types.contains("pub const DepositResult = union(enum) {"));
    assert!(types.contains("claim_response: ClaimResponse,"));
    assert!(types.contains("service_error: ServiceError,"));
    assert!(types.contains("pub fn variant_name(self: DepositResult) []const u8"));
    assert!(types.contains(".service_error => \"ServiceError\","));
}

#[test]
fn text_choice_field_maps_to_string_slice() {
    // `text / "a" / "b"` is a string with a suggested value set; on the wire it is a
    // text string, so it must map to []const u8, not the opaque dynamic fallback.
    let rule = CsilRule {
        name: "Status".to_string(),
        rule_type: CsilRuleType::TypeDef(CsilTypeExpression::Choice(vec![
            builtin("text"),
            CsilTypeExpression::Literal(CsilLiteralValue::Text("open".to_string())),
            CsilTypeExpression::Literal(CsilLiteralValue::Text("closed".to_string())),
        ])),
        position: pos(),
        doc_comments: vec![],
    };
    let input = input_with_rules(vec![rule], "zig", HashMap::new());
    let config = ZigConfig::from_options(&input.config.options).unwrap();
    let types = generate_types(&input, &config).unwrap();
    assert!(types.contains("pub const Status = []const u8;"));
    assert!(!types.contains("anyopaque"));
}

#[test]
fn acronyms_snake_case_as_one_word() {
    // A service with an acronym in its name produces readable snake_case symbols
    // (api_error, not a_p_i_error) for the validate/router/encoder function names.
    assert_eq!(to_snake("APIError"), "api_error");
    assert_eq!(to_snake("ECommerceAPI"), "e_commerce_api");
    assert_eq!(to_snake("deposit-claim"), "deposit_claim");
    assert_eq!(to_snake("views_last_30d"), "views_last_30d");
}

#[test]
fn reserved_word_field_is_quoted() {
    let input = input_with_rules(
        vec![group_rule(
            "Wrapper",
            vec![
                bare_entry("error", builtin("text")),
                bare_entry("type", builtin("text")),
            ],
        )],
        "zig",
        HashMap::new(),
    );
    let config = ZigConfig::from_options(&input.config.options).unwrap();
    let types = generate_types(&input, &config).unwrap();
    assert!(types.contains("@\"error\": []const u8,"));
    assert!(types.contains("@\"type\": []const u8,"));
}

#[test]
fn types_emitted_in_by_value_dependency_order() {
    // Outer embeds Inner by value, but is declared first; the topo sort must emit
    // Inner before Outer so a by-value member's type is seen first.
    let outer = group_rule(
        "Outer",
        vec![bare_entry(
            "inner",
            CsilTypeExpression::Reference("Inner".to_string()),
        )],
    );
    let inner = group_rule("Inner", vec![bare_entry("n", builtin("int"))]);
    let input = input_with_rules(vec![outer, inner], "zig", HashMap::new());
    let config = ZigConfig::from_options(&input.config.options).unwrap();
    let types = generate_types(&input, &config).unwrap();
    let inner_at = types.find("pub const Inner = struct").unwrap();
    let outer_at = types.find("pub const Outer = struct").unwrap();
    assert!(
        inner_at < outer_at,
        "Inner must be emitted before Outer:\n{types}"
    );
}

#[test]
fn optional_reference_does_not_force_order() {
    // An optional reference is a `?T` and does not constrain order, so Outer may
    // precede Inner; both must still be present.
    let mut entry = bare_entry("inner", CsilTypeExpression::Reference("Inner".to_string()));
    entry.occurrence = Some(CsilOccurrence::Optional);
    let outer = group_rule("Outer", vec![entry]);
    let inner = group_rule("Inner", vec![bare_entry("n", builtin("int"))]);
    let input = input_with_rules(vec![outer, inner], "zig", HashMap::new());
    let config = ZigConfig::from_options(&input.config.options).unwrap();
    let types = generate_types(&input, &config).unwrap();
    assert!(types.contains("inner: ?Inner = null,"));
    assert!(types.contains("pub const Inner = struct"));
}

#[test]
fn client_emits_typed_struct_with_verbatim_wire_names() {
    let svc = service_rule(
        "AttestationService",
        vec![op(
            "deposit-claim",
            CsilTypeExpression::Reference("DepositClaimRequest".to_string()),
            CsilTypeExpression::Reference("DepositClaimResponse".to_string()),
            CsilServiceDirection::Unidirectional,
            None,
        )],
        None,
    );
    let input = input_with_rules(vec![svc], "zig-client", HashMap::new());
    let client = generate_client(&input).expect("client emitted");
    assert!(client.contains("pub const AttestationClient = struct"));
    // kebab -> snake for the Zig method; service base lowercased and op PascalCased
    // for the wire strings.
    assert!(
        client.contains(
            "pub fn deposit_claim(self: AttestationClient, req: []const u8) anyerror![]u8"
        )
    );
    assert!(client.contains("\"attestation\", \"DepositClaim\""));
    assert!(client.contains("CsilgenTransport"));
}

#[test]
fn server_emits_handlers_wire_ids_and_compact_router() {
    let svc = service_rule(
        "ChatService",
        vec![
            op(
                "say",
                CsilTypeExpression::Reference("SayMessage".to_string()),
                builtin("nil"),
                CsilServiceDirection::Bidirectional,
                Some(0),
            ),
            op(
                "ping",
                builtin("nil"),
                CsilTypeExpression::Reference("Pong".to_string()),
                CsilServiceDirection::Unidirectional,
                Some(1),
            ),
        ],
        Some(7),
    );
    let input = input_with_rules(vec![svc], "zig", HashMap::new());
    let mut warnings = Vec::new();
    let server = generate_server(&input, &mut warnings).expect("server emitted");
    assert!(server.contains("pub const ChatHandlers = struct {"));
    // Bidirectional handler is fire-and-forget; unidirectional has a response out.
    assert!(
        server.contains(
            "say: *const fn (ctx: *anyopaque, msg: *const types.SayMessage) anyerror!void,"
        )
    );
    assert!(server.contains("ping: *const fn (ctx: *anyopaque, resp: *types.Pong) anyerror!void,"));
    assert!(server.contains("pub const chat_service_wire_id: u64 = 7;"));
    assert!(server.contains("pub const chat_op_say_wire_id: u64 = 0;"));
    // Verbose + compact router twins.
    assert!(server.contains("pub fn route_chat_channel("));
    assert!(server.contains("pub fn route_chat_channel_compact("));
    assert!(server.contains("std.mem.eql(u8, method, \"Say\")"));
    assert!(server.contains("        0 => {"));
}

#[test]
fn compact_router_absent_without_wire_id() {
    let svc = service_rule(
        "ChatService",
        vec![op(
            "say",
            CsilTypeExpression::Reference("SayMessage".to_string()),
            builtin("nil"),
            CsilServiceDirection::Bidirectional,
            None,
        )],
        None,
    );
    let input = input_with_rules(vec![svc], "zig", HashMap::new());
    let mut warnings = Vec::new();
    let server = generate_server(&input, &mut warnings).unwrap();
    assert!(server.contains("pub fn route_chat_channel("));
    assert!(!server.contains("route_chat_channel_compact("));
    assert!(!server.contains("wire_id"));
}

#[test]
fn validation_emits_predicate_for_constraints() {
    let entry = CsilGroupEntry {
        key: Some(CsilGroupKey::Bare("name".to_string())),
        value_type: builtin("text"),
        occurrence: None,
        metadata: vec![CsilFieldMetadata::Constraint(
            CsilValidationConstraint::MinLength(3),
        )],
        doc_comments: vec![],
    };
    let input = input_with_rules(vec![group_rule("User", vec![entry])], "zig", HashMap::new());
    let validation = generate_validation(&input).expect("validation emitted");
    assert!(validation.contains("pub fn validate_user(v: *const types.User) bool {"));
    assert!(validation.contains("if (v.name.len < 3) return false;"));
}

#[test]
fn validation_optional_numeric_is_guarded_and_cast() {
    let mut entry = bare_entry(
        "age",
        CsilTypeExpression::Constrained {
            base_type: Box::new(builtin("uint")),
            constraints: vec![CsilControlOperator::GreaterEqual(
                CsilLiteralValue::Integer(18),
            )],
        },
    );
    entry.occurrence = Some(CsilOccurrence::Optional);
    let input = input_with_rules(
        vec![group_rule("Person", vec![entry])],
        "zig",
        HashMap::new(),
    );
    let validation = generate_validation(&input).expect("validation emitted");
    assert!(validation.contains(
        "if (v.age) |x| {\n        if (@as(i64, @intCast(x)) < 18) return false;\n    }"
    ));
}

#[test]
fn validation_omitted_without_checks() {
    let input = input_with_rules(
        vec![group_rule(
            "User",
            vec![bare_entry("name", builtin("text"))],
        )],
        "zig",
        HashMap::new(),
    );
    assert!(generate_validation(&input).is_none());
}

#[test]
fn typesonly_omits_service_surface() {
    let svc = service_rule(
        "ChatService",
        vec![op(
            "ping",
            builtin("nil"),
            CsilTypeExpression::Reference("Pong".to_string()),
            CsilServiceDirection::Unidirectional,
            None,
        )],
        None,
    );
    let out =
        process_generation(input_with_rules(vec![svc], "zig-typesonly", HashMap::new())).unwrap();
    assert!(!out.files.iter().any(|f| f.path == "server.gen.zig"));
    assert!(!out.files.iter().any(|f| f.path == "client.gen.zig"));
}

#[test]
fn unknown_subtarget_is_a_hard_error() {
    let input = input_with_rules(
        vec![group_rule(
            "User",
            vec![bare_entry("name", builtin("text"))],
        )],
        "zig-bogus",
        HashMap::new(),
    );
    assert!(process_generation(input).is_err());
}

#[test]
fn unknown_decimal_mapping_is_a_hard_error() {
    let mut opts = HashMap::new();
    opts.insert("decimal_mapping".to_string(), serde_json::json!("nonsense"));
    let input = input_with_rules(
        vec![group_rule(
            "User",
            vec![bare_entry("name", builtin("text"))],
        )],
        "zig",
        opts,
    );
    assert!(process_generation(input).is_err());
}

#[test]
fn metadata_advertises_zig_target() {
    let ptr = get_metadata();
    assert!(!ptr.is_null());
    let len = unsafe { std::ptr::read(ptr as *const u32) } as usize;
    let json = unsafe { std::slice::from_raw_parts(ptr.add(4), len) };
    let meta: GeneratorMetadata = serde_json::from_slice(json).unwrap();
    assert_eq!(meta.target, "zig");
}
