//! Tests for YAML struct tag generation

use csilgen_common::*;
use std::collections::HashMap;

/// Test that both JSON and YAML tags are generated by default
#[test]
fn test_yaml_and_json_tags_generated() {
    let input = create_test_input_with_config(true, true);

    // Note: This test validates the structure is correct
    // Actual tag generation is tested at the CLI/integration level
    assert!(input.config.options.get("use_json_tags").and_then(|v| v.as_bool()).unwrap_or(false));
    assert!(input.config.options.get("use_yaml_tags").and_then(|v| v.as_bool()).unwrap_or(false));
}

/// Test that only JSON tags are generated when YAML is disabled
#[test]
fn test_json_only_tags() {
    let input = create_test_input_with_config(true, false);

    assert!(input.config.options.get("use_json_tags").and_then(|v| v.as_bool()).unwrap_or(false));
    assert!(!input.config.options.get("use_yaml_tags").and_then(|v| v.as_bool()).unwrap_or(true));
}

/// Test optional fields get omitempty in both tags
#[test]
fn test_optional_field_omitempty() {
    let input = create_test_input_with_optional_field();

    // Verify we have an optional field in the spec
    if let Some(CsilRuleType::GroupDef(group)) = input.csil_spec.rules.get(0).map(|r| &r.rule_type) {
        let optional_field = group.entries.iter().find(|e| matches!(e.occurrence, Some(CsilOccurrence::Optional)));
        assert!(optional_field.is_some(), "Should have at least one optional field");
    }
}

/// Helper to create test input with specific config options
fn create_test_input_with_config(use_json: bool, use_yaml: bool) -> WasmGeneratorInput {
    let metadata = GeneratorMetadata {
        name: "go-generator".to_string(),
        version: "1.0.0".to_string(),
        description: "Go code generator".to_string(),
        target: "go".to_string(),
        capabilities: vec![GeneratorCapability::BasicTypes],
        author: Some("CSIL Team".to_string()),
        homepage: Some("https://github.com/catalystcommunity/csilgen".to_string()),
    };

    let mut options = HashMap::new();
    options.insert("package_name".to_string(), serde_json::Value::String("api".to_string()));
    options.insert("use_json_tags".to_string(), serde_json::Value::Bool(use_json));
    options.insert("use_yaml_tags".to_string(), serde_json::Value::Bool(use_yaml));

    let config = GeneratorConfig {
        target: "go".to_string(),
        output_dir: "/tmp/output".to_string(),
        options,
    };

    let spec = CsilSpecSerialized {
        rules: vec![CsilRule {
            name: "TestStruct".to_string(),
            rule_type: CsilRuleType::GroupDef(CsilGroupExpression {
                entries: vec![
                    CsilGroupEntry {
                        key: Some(CsilGroupKey::Bare("name".to_string())),
                        value_type: CsilTypeExpression::Builtin("text".to_string()),
                        occurrence: None,
                        metadata: vec![],
                    },
                ],
            }),
            position: CsilPosition { line: 1, column: 1, offset: 0 },
        }],
        source_content: None,
        service_count: 0,
        fields_with_metadata_count: 0,
    };

    WasmGeneratorInput {
        csil_spec: spec,
        config,
        generator_metadata: metadata,
    }
}

/// Helper to create test input with an optional field
fn create_test_input_with_optional_field() -> WasmGeneratorInput {
    let metadata = GeneratorMetadata {
        name: "go-generator".to_string(),
        version: "1.0.0".to_string(),
        description: "Go code generator".to_string(),
        target: "go".to_string(),
        capabilities: vec![GeneratorCapability::BasicTypes],
        author: Some("CSIL Team".to_string()),
        homepage: Some("https://github.com/catalystcommunity/csilgen".to_string()),
    };

    let config = GeneratorConfig {
        target: "go".to_string(),
        output_dir: "/tmp/output".to_string(),
        options: {
            let mut opts = HashMap::new();
            opts.insert("package_name".to_string(), serde_json::Value::String("api".to_string()));
            opts
        },
    };

    let spec = CsilSpecSerialized {
        rules: vec![CsilRule {
            name: "User".to_string(),
            rule_type: CsilRuleType::GroupDef(CsilGroupExpression {
                entries: vec![
                    CsilGroupEntry {
                        key: Some(CsilGroupKey::Bare("name".to_string())),
                        value_type: CsilTypeExpression::Builtin("text".to_string()),
                        occurrence: None,
                        metadata: vec![],
                    },
                    CsilGroupEntry {
                        key: Some(CsilGroupKey::Bare("email".to_string())),
                        value_type: CsilTypeExpression::Builtin("text".to_string()),
                        occurrence: Some(CsilOccurrence::Optional),
                        metadata: vec![],
                    },
                ],
            }),
            position: CsilPosition { line: 1, column: 1, offset: 0 },
        }],
        source_content: None,
        service_count: 0,
        fields_with_metadata_count: 0,
    };

    WasmGeneratorInput {
        csil_spec: spec,
        config,
        generator_metadata: metadata,
    }
}
