name: csilgen-release-tag
description: "Create draft releases and push changed csilgen tags."
triggers:
  events:
    - pull_request_merged
  branches:
    - main
job:
  image: containers.catalystsquad.com/public/reactorcide/runnerbase:latest
  command: "runnerlib run --job-command true"
  timeout: 900
  priority: 15
  working_dir: /job
  disable_run_local: true
environment:
  REACTORCIDE_CSILGEN_JOB: release-tag
  REACTORCIDE_REPO: catalystcommunity/csilgen
  GITHUB_PAT: "${secret:catalystcommunity/ci:githubpat}"
