name: csilgen-test-transports
description: "Run all transport conformance tests."
triggers:
  events:
    - pull_request_opened
    - pull_request_updated
  branches:
    - main
job:
  image: containers.catalystsquad.com/private/catalystcommunity/csilgen/ci-toolchain@sha256:3bc81e33f1abfac291e663e6692428a8376f3d1c9d44fd47dfb38d7726a07a90
  command: "runnerlib run --job-command true"
  timeout: 3600
  priority: 10
  working_dir: /job
  depends_on:
    - csilgen-conventional-commits
environment:
  CSILGEN_JOB: transports
  GOPATH: /job/cache/go
  GOMODCACHE: /job/cache/go/pkg/mod
  GOCACHE: /job/cache/go-build
run_local:
  user: root
