//! Shared helpers for the TypeScript emitters (types / client / server).

use csilgen_common::{
    CsilOccurrence, CsilRuleType, CsilServiceDefinition, CsilServiceDirection,
    CsilServiceOperation, CsilSpecSerialized, CsilTypeExpression, WasmGeneratorInput,
};
use std::collections::BTreeSet;

/// Bidirectional transport mode declared in the CSIL options block. Generators
/// emit shapes for *messages and routing*, never the wire — these values
/// describe how the consumer's implementation is going to wire up.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BidiTransport {
    /// Long-lived connection (WebSocket/TCP). Channels are push-based:
    /// implementer feeds inbound frames into a router, sends outbound via the
    /// generated encoders. Default.
    Connection,
    /// Request-response only (no persistent channel). Bidirectional ops
    /// degrade to a `check<Op>` poll for inbound + `send<Op>` for outbound,
    /// both riding the existing `ServiceTransport.call`.
    Rpc,
}

/// Read & validate `ts_bidirectional_transport` from the CSIL options block.
/// Any non-`connection`/`rpc` value is rejected so misconfiguration surfaces
/// at generation time instead of silently degrading.
pub fn bidi_transport(input: &WasmGeneratorInput) -> Result<BidiTransport, String> {
    match input.config.options.get("ts_bidirectional_transport") {
        None => Ok(BidiTransport::Connection),
        Some(v) => match v.as_str() {
            Some("connection") => Ok(BidiTransport::Connection),
            Some("rpc") => Ok(BidiTransport::Rpc),
            Some(other) => Err(format!(
                "ts_bidirectional_transport must be \"connection\" or \"rpc\", got {other:?}"
            )),
            None => Err(format!(
                "ts_bidirectional_transport must be a string, got {v:?}"
            )),
        },
    }
}

pub fn is_unidirectional(op: &CsilServiceOperation) -> bool {
    matches!(op.direction, CsilServiceDirection::Unidirectional)
}

pub fn is_bidirectional(op: &CsilServiceOperation) -> bool {
    matches!(op.direction, CsilServiceDirection::Bidirectional)
}

pub fn is_reverse(op: &CsilServiceOperation) -> bool {
    matches!(op.direction, CsilServiceDirection::Reverse)
}

/// True if the service has any operation that is not a plain request/response,
/// i.e. it needs the bidirectional channel emissions.
pub fn service_has_channel_ops(def: &CsilServiceDefinition) -> bool {
    def.operations.iter().any(|op| !is_unidirectional(op))
}

/// Standard `DO NOT EDIT` banner. `target` distinguishes the emitter.
pub fn header(input: &WasmGeneratorInput, target: &str) -> String {
    let source = input
        .csil_spec
        .source_content
        .as_deref()
        .map(|_| "<csil spec>")
        .unwrap_or("<csil spec>");
    format!(
        "// Code generated by csilgen. DO NOT EDIT.\n// Source: {source}\n// Target: {target}\n\n"
    )
}

/// Whether the spec declares at least one service.
pub fn has_services(spec: &CsilSpecSerialized) -> bool {
    spec.rules
        .iter()
        .any(|r| matches!(r.rule_type, CsilRuleType::ServiceDef(_)))
}

/// Services sorted by rule name for deterministic output.
pub fn sorted_services(spec: &CsilSpecSerialized) -> Vec<(&str, &CsilServiceDefinition)> {
    let mut services: Vec<(&str, &CsilServiceDefinition)> = spec
        .rules
        .iter()
        .filter_map(|r| match &r.rule_type {
            CsilRuleType::ServiceDef(def) => Some((r.name.as_str(), def)),
            _ => None,
        })
        .collect();
    services.sort_by(|a, b| a.0.cmp(b.0));
    services
}

/// Map a CSIL type expression to a TypeScript type string.
pub fn ts_type(type_expr: &CsilTypeExpression) -> String {
    match type_expr {
        CsilTypeExpression::Builtin(name) => builtin(name),
        CsilTypeExpression::Reference(name) => to_pascal(name),
        CsilTypeExpression::Array { element_type, .. } => format!("{}[]", ts_type(element_type)),
        CsilTypeExpression::Map { value, .. } => format!("Record<string, {}>", ts_type(value)),
        CsilTypeExpression::Choice(choices) => {
            choices.iter().map(ts_type).collect::<Vec<_>>().join(" | ")
        }
        CsilTypeExpression::Range { .. } => "number".to_string(),
        // Constrained types reduce to their base type in TypeScript
        CsilTypeExpression::Constrained { base_type, .. } => ts_type(base_type),
        CsilTypeExpression::Socket(name) | CsilTypeExpression::Plug(name) => to_pascal(name),
        // Inline groups and bare literals are uncommon in operation signatures;
        // fall back to a permissive type so output still compiles.
        CsilTypeExpression::Group(_) => "object".to_string(),
        CsilTypeExpression::Literal(_) => "unknown".to_string(),
    }
}

fn builtin(name: &str) -> String {
    match name {
        "text" | "string" => "string",
        "int" | "uint" | "integer" | "float" | "float16" | "float32" | "float64" | "number" => {
            "number"
        }
        "bool" | "boolean" => "boolean",
        "bytes" => "Uint8Array",
        "null" => "null",
        "any" => "any",
        _ => "unknown",
    }
    .to_string()
}

/// Collect every user-defined type name referenced by a type expression.
pub fn collect_type_refs(type_expr: &CsilTypeExpression, out: &mut BTreeSet<String>) {
    match type_expr {
        CsilTypeExpression::Reference(name)
        | CsilTypeExpression::Socket(name)
        | CsilTypeExpression::Plug(name) => {
            out.insert(to_pascal(name));
        }
        CsilTypeExpression::Array { element_type, .. } => collect_type_refs(element_type, out),
        CsilTypeExpression::Map { key, value, .. } => {
            collect_type_refs(key, out);
            collect_type_refs(value, out);
        }
        CsilTypeExpression::Choice(choices) => {
            for c in choices {
                collect_type_refs(c, out);
            }
        }
        CsilTypeExpression::Constrained { base_type, .. } => collect_type_refs(base_type, out),
        CsilTypeExpression::Group(group) => {
            for entry in &group.entries {
                collect_type_refs(&entry.value_type, out);
            }
        }
        CsilTypeExpression::Builtin(_)
        | CsilTypeExpression::Range { .. }
        | CsilTypeExpression::Literal(_) => {}
    }
}

/// The transport-level error type name. When an operation's output is written
/// as `Success / ServiceError`, the error half is thrown rather than returned,
/// so it is stripped from the success type the client/server signatures use.
pub const SERVICE_ERROR: &str = "ServiceError";

/// Drop a top-level `ServiceError` member from a choice output. Domain error
/// types (anything not named `ServiceError`) are left in place because they are
/// returned values, not thrown.
pub fn success_type(type_expr: &CsilTypeExpression) -> CsilTypeExpression {
    if let CsilTypeExpression::Choice(choices) = type_expr {
        let kept: Vec<CsilTypeExpression> = choices
            .iter()
            .filter(|c| !is_service_error(c))
            .cloned()
            .collect();
        match kept.len() {
            0 => type_expr.clone(),
            1 => kept.into_iter().next().unwrap(),
            _ => CsilTypeExpression::Choice(kept),
        }
    } else {
        type_expr.clone()
    }
}

fn is_service_error(type_expr: &CsilTypeExpression) -> bool {
    matches!(type_expr, CsilTypeExpression::Reference(name) if to_pascal(name) == SERVICE_ERROR)
}

/// All type names referenced across the request/response signatures of the
/// given services, sorted for deterministic imports. Output types are reduced
/// to their success form first, so a thrown `ServiceError` is not imported.
pub fn referenced_types(services: &[(&str, &CsilServiceDefinition)]) -> Vec<String> {
    let mut set = BTreeSet::new();
    for (_, def) in services {
        for op in &def.operations {
            collect_type_refs(&op.input_type, &mut set);
            collect_type_refs(&success_type(&op.output_type), &mut set);
        }
    }
    set.into_iter().collect()
}

/// Is this occurrence an optional field marker?
pub fn is_optional(occurrence: &Option<CsilOccurrence>) -> bool {
    matches!(occurrence, Some(CsilOccurrence::Optional))
}

/// PascalCase for type names (`house_id` -> `HouseID`-style is not attempted;
/// segments are simply capitalised: `house_id` -> `HouseId`).
pub fn to_pascal(name: &str) -> String {
    let mut out = String::new();
    let mut cap = true;
    for c in name.chars() {
        if c == '_' || c == '-' {
            cap = true;
        } else if cap {
            out.extend(c.to_uppercase());
            cap = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// camelCase for field and method names.
pub fn to_camel(name: &str) -> String {
    let pascal = to_pascal(name);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().chain(chars).collect(),
        None => String::new(),
    }
}

/// Strip a trailing `Service` suffix: `AuthService` -> `Auth`, `Auth` -> `Auth`.
pub fn service_base(name: &str) -> String {
    let pascal = to_pascal(name);
    pascal
        .strip_suffix("Service")
        .filter(|s| !s.is_empty())
        .map(str::to_string)
        .unwrap_or(pascal)
}

/// The string passed to the transport for a service: lowercase of the base name.
pub fn service_wire(name: &str) -> String {
    service_base(name).to_lowercase()
}

/// The string passed to the transport for a method: PascalCase of the op name.
pub fn method_wire(op: &CsilServiceOperation) -> String {
    to_pascal(&op.name)
}

/// Render a JSDoc block from doc comments plus any extra trailing lines.
/// Returns an empty string when there is nothing to document.
pub fn jsdoc(doc_comments: &[String], extra: &[String], indent: &str) -> String {
    if doc_comments.is_empty() && extra.is_empty() {
        return String::new();
    }
    let mut out = format!("{indent}/**\n");
    for line in doc_comments {
        out.push_str(&format!("{indent} * {line}\n"));
    }
    for line in extra {
        out.push_str(&format!("{indent} * {line}\n"));
    }
    out.push_str(&format!("{indent} */\n"));
    out
}
