//! Self-contained, publishable npm-package emission.
//!
//! When `emit_packages` includes `"typescript"`, the generator turns the output
//! directory into a buildable npm package: a barrel `index.ts`, a `package.json`,
//! and a `tsconfig.json`. The generated `.gen.ts` modules import each other with
//! `.ts`-extensioned relative specifiers (`./types.gen.ts`) so consumers can run
//! the sources directly under Node's ESM type stripping and typecheck under
//! `nodenext`; the shipped tsconfig therefore enables
//! `rewriteRelativeImportExtensions` (TS 5.7+) so its own CommonJS `dist/` build
//! rewrites them to `.js` on emit.

use crate::{codec, common};
use csilgen_common::{
    CsilGroupExpression, CsilGroupKey, CsilOccurrence, CsilRuleType, CsilTypeExpression,
    GeneratedFile, WasmGeneratorInput,
};
use std::collections::BTreeSet;

/// Whether the consumer asked for a TypeScript package. The option is a JSON
/// array of target ids; a lone string is accepted too so a hand-written config
/// (`"emit_packages": "typescript"`) still works. Anything else means "no".
pub fn wants_typescript_package(input: &WasmGeneratorInput) -> bool {
    match input.config.options.get("emit_packages") {
        Some(serde_json::Value::Array(items)) => {
            items.iter().any(|v| v.as_str() == Some("typescript"))
        }
        Some(serde_json::Value::String(s)) => s == "typescript",
        _ => false,
    }
}

/// Append the package scaffolding (barrel + `package.json` + `tsconfig.json`) to
/// the already-generated module files. A no-op unless `emit_packages` opts in.
pub fn augment(input: &WasmGeneratorInput, files: &mut Vec<GeneratedFile>) {
    if !wants_typescript_package(input) {
        return;
    }

    let barrel = barrel(input, files);
    files.push(GeneratedFile {
        path: "index.ts".to_string(),
        content: barrel,
    });
    files.push(GeneratedFile {
        path: "package.json".to_string(),
        content: package_json(input),
    });
    files.push(GeneratedFile {
        path: "tsconfig.json".to_string(),
        content: TSCONFIG.to_string(),
    });
    // The README is the one piece a consumer can opt out of: only an explicit
    // `emit_readme: false` suppresses it, so a missing or non-bool value (and `true`)
    // leaves the default-on behavior untouched.
    if wants_readme(input) {
        files.push(GeneratedFile {
            path: "genquickstart.md".to_string(),
            content: readme(input),
        });
    }
}

/// Whether to emit the package `genquickstart.md`. Default true; only an explicit
/// `emit_readme: false` suppresses it.
fn wants_readme(input: &WasmGeneratorInput) -> bool {
    input
        .config
        .options
        .get("emit_readme")
        .and_then(|v| v.as_bool())
        != Some(false)
}

/// Which transport sections a consumer wants in `genquickstart.md`. The
/// `genquickstart_transports` option is a JSON array subset of
/// `["rpc","events","datagrams"]`; unknown entries are ignored, and an absent or
/// empty value means "all three". Three sections always render in a fixed order so
/// the document reads the same regardless of how the subset was written.
fn wanted_transports(input: &WasmGeneratorInput) -> (bool, bool, bool) {
    let listed = match input.config.options.get("genquickstart_transports") {
        Some(serde_json::Value::Array(items)) => {
            let names: BTreeSet<&str> = items.iter().filter_map(|v| v.as_str()).collect();
            // An array that names none of the known transports (all entries unknown,
            // or an empty array) falls back to all three rather than an empty doc.
            let any_known = ["rpc", "events", "datagrams"]
                .iter()
                .any(|t| names.contains(t));
            if any_known {
                Some((
                    names.contains("rpc"),
                    names.contains("events"),
                    names.contains("datagrams"),
                ))
            } else {
                None
            }
        }
        _ => None,
    };
    listed.unwrap_or((true, true, true))
}

/// The package README: a transport-by-transport Quickstart over the official
/// `csilgen-transport` library. The generated codec owns CBOR (de)serialization and
/// the library owns the envelope/framing/lifecycle; you supply only a *carrier* that
/// moves bytes. Each requested section (CSIL-RPC over HTTP, CSIL-Events over TLS,
/// CSIL-Datagrams over UDP) is a complete, copy-paste example built on the library.
fn readme(input: &WasmGeneratorInput) -> String {
    let name = package_name(input);
    let mut out = format!(
        "# {name}\n\n\
         Generated by csilgen. A typed CSIL client: the generated codec owns CBOR\n\
         (de)serialization and the [`csilgen-transport`](https://www.npmjs.com/package/csilgen-transport)\n\
         library owns the envelope, framing, and connection lifecycle. You supply only a\n\
         *carrier* that moves bytes, so the same typed surface rides HTTP, TLS, a\n\
         WebSocket, WebRTC, QUIC, or raw UDP unchanged.\n\n\
         ## Install\n\n\
         ```sh\n\
         npm install {name} csilgen-transport\n\
         ```\n\n\
         The generated modules import each other with `.ts`-extensioned relative\n\
         specifiers (`./types.gen.ts`), matching this package's `tsconfig.json`\n\
         (`rewriteRelativeImportExtensions`) and Node's ESM loader. Regenerating\n\
         outside of package mode — a bare `csilgen generate --target typescript`\n\
         dropped into an existing project — pass `import_extension: \"js\"` or\n\
         `\"none\"` to match a project that does not enable that TypeScript 5.7+\n\
         flag.\n\n"
    );

    let (rpc, events, datagrams) = wanted_transports(input);
    let unary = first_unary_example(input);
    let channel = first_channel_example(input);
    if rpc {
        out.push_str(&rpc_section(input, &name, unary.as_ref()));
    }
    if events {
        out.push_str(&events_section(&name, channel.as_ref()));
    }
    if datagrams {
        out.push_str(&datagrams_section(&name, unary.as_ref()));
    }
    out
}

/// CSIL-RPC over HTTP: a carrier implementing the generated async byte seam
/// (`AsyncServiceTransport`) that builds/parses the envelope with the library's
/// `RpcRequest`/`RpcResponse` (never hand-rolled) and POSTs it to
/// `{baseUrl}/csil/v1/rpc`. The typed client decodes the success payload; a non-zero
/// transport status and the `ServiceError` application arm are surfaced distinctly.
fn rpc_section(input: &WasmGeneratorInput, pkg: &str, ex: Option<&UnaryExample>) -> String {
    let mut out = String::from("## CSIL-RPC (HTTP)\n\n");
    out.push_str(
        "Request/response. The library owns the envelope (`RpcRequest`/`RpcResponse`);\n\
         you bring a carrier that moves bytes. The HTTP carrier below is just one\n\
         example — swap `fetch` for any client (it implements the generated byte seam).\n\n",
    );
    let Some(ex) = ex else {
        out.push_str(
            "This package declares no `->` operations, so there is no RPC call to make.\n\n",
        );
        return out;
    };
    let configured =
        option_string(input, "aggregate_class_name").unwrap_or_else(|| "ApiClient".to_string());
    let aggregate = format!("Async{configured}");
    out.push_str("```ts\n");
    out.push_str("import { RpcRequest, RpcResponse } from \"csilgen-transport\";\n");
    out.push_str(&format!(
        "import {{ {aggregate}, type AsyncServiceTransport }} from \"{pkg}\";\n\n"
    ));
    out.push_str(RPC_CARRIER_TS);
    out.push('\n');
    out.push_str(&format!(
        "async function main() {{\n  const client = new {aggregate}(new HttpRpcCarrier(\"http://localhost:5080\"));\n  "
    ));
    if ex.has_request {
        out.push_str(&format!(
            "const resp = await client.{}.{}({});\n  ",
            ex.service_field, ex.method, ex.sample
        ));
    } else {
        out.push_str(&format!(
            "const resp = await client.{}.{}();\n  ",
            ex.service_field, ex.method
        ));
    }
    out.push_str("console.log(resp);\n}\n\nmain();\n```\n\n");
    out
}

/// The HTTP carrier body — spec-independent, so a constant. It encodes the request
/// envelope with the library's `RpcRequest`, POSTs it to `{baseUrl}/csil/v1/rpc`, and
/// returns the success payload bytes the typed client decodes. `RpcResponse.decode`
/// plus `intoTransportError` throws on a non-zero transport status; the typed
/// `ServiceError` arm (a status-0 variant) is surfaced separately.
const RPC_CARRIER_TS: &str = r#"// One example carrier: CSIL-RPC over an HTTP POST. The library owns the envelope;
// the carrier owns only the transport. Swap `fetch` for any HTTP client.
class HttpRpcCarrier implements AsyncServiceTransport {
  constructor(private readonly baseUrl: string) {}

  async call(service: string, op: string, req: Uint8Array): Promise<Uint8Array> {
    const envelope = new RpcRequest(service, op, req).encode();
    const http = await fetch(this.baseUrl.replace(/\/+$/, "") + "/csil/v1/rpc", {
      method: "POST",
      headers: { "Content-Type": "application/cbor", Accept: "application/cbor" },
      // `Uint8Array` is a valid fetch body at runtime; the cast satisfies the DOM
      // `BodyInit` typing.
      body: envelope as BodyInit,
    });
    if (!http.ok) throw new Error(`csil-rpc ${service}/${op}: http ${http.status}`);

    // `intoTransportError` throws a `TransportError` for any non-zero transport status.
    const resp = RpcResponse.decode(
      new Uint8Array(await http.arrayBuffer()),
    ).intoTransportError();
    // A typed application error rides as a status-0 `ServiceError` variant — distinct
    // from a transport failure. Surface it so the typed client decodes success only.
    if (resp.variant === "ServiceError") {
      throw new Error(`csil-rpc ${service}/${op}: ServiceError`);
    }
    return resp.payload;
  }
}
"#;

/// CSIL-Events over TLS: a full session example. Opens a TLS byte stream wrapped as
/// the library's `FrameCarrier` (CSIL length-prefix framing), performs the
/// `$hello`/`$hello-ack` handshake, sends one outbound event via the generated
/// `encode<Service><Op>`, and runs a recv loop that decodes each frame to an `Event`,
/// answers `$ping` with `$pong`, and dispatches typed events to the generated
/// `route<Service>Channel`. When the spec has no channel ops the dispatch wiring is
/// replaced with a note (the handshake + heartbeat still apply to any connection).
fn events_section(pkg: &str, ch: Option<&ChannelExample>) -> String {
    let mut out = String::from("## CSIL-Events (TLS)\n\n");
    out.push_str(
        "Typed, bidirectional event streams over a long-lived connection. The library\n\
         owns the `$hello`/`$hello-ack` handshake, the `$ping`/`$pong` heartbeat, and\n\
         framing; the generated router dispatches typed events. The TLS carrier below is\n\
         just one example — a WebSocket/WebTransport/QUIC carrier drops in unchanged.\n\n",
    );
    out.push_str("```ts\n");
    out.push_str(
        "import {\n  Event,\n  Hello,\n  HelloAck,\n  Heartbeat,\n  control,\n  \
         frameLengthPrefixed,\n  LengthPrefixedDeframer,\n  MAX_FRAME_DEFAULT,\n  \
         type FrameCarrier,\n  type Profile,\n} from \"csilgen-transport\";\n",
    );
    out.push_str("import * as tls from \"node:tls\";\n");
    match ch {
        Some(ch) => {
            out.push_str(&format!(
                "import {{\n  {route},\n  type {handlers},\n  {encode},\n  type Codec,\n}} from \"{pkg}\";\n",
                route = ch.route_fn,
                handlers = ch.handlers_iface,
                encode = ch.encode_fn,
            ));
            // decode handles the inbound record; encode handles the outbound record.
            out.push_str(&format!(
                "import {{ from{inbound}Cbor, to{outbound}Cbor }} from \"{pkg}\";\n",
                inbound = ch.inbound_type,
                outbound = ch.outbound_type,
            ));
            out.push_str(&format!(
                "import type {{ {outbound} }} from \"{pkg}\";\n\n",
                outbound = ch.outbound_type,
            ));
        }
        None => out.push('\n'),
    }
    out.push_str(EVENTS_CARRIER_TS);
    out.push('\n');
    match ch {
        Some(ch) => out.push_str(&events_session(ch)),
        None => out.push_str(EVENTS_NO_CHANNEL_SESSION_TS),
    }
    out.push_str("```\n\n");
    out
}

/// The TLS `FrameCarrier` adapter — spec-independent. It length-prefixes each
/// outbound frame and feeds inbound socket chunks through a `LengthPrefixedDeframer`,
/// exposing the library's `sendFrame`/`recvFrame` seam so the session logic is
/// transport-agnostic.
const EVENTS_CARRIER_TS: &str = r#"// One example carrier: a TLS byte stream framed with CSIL's 4-byte length prefix.

// The max-frame guard is a carrier setting, not a generated constant: raise it when a peer
// accepts payloads larger than the 16 MiB default (the envelope adds framing and request
// metadata around the payload, so the limit must exceed the largest payload), or lower it
// to harden an exposed listener. Valid limits are 1..=MAX_FRAME_LIMIT and are checked where
// the deframer is built.
const MAX_FRAME = MAX_FRAME_DEFAULT;

function openTlsCarrier(host: string, port: number): FrameCarrier {
  const socket = tls.connect({ host, port });
  const deframer = new LengthPrefixedDeframer(MAX_FRAME);
  const inbox: Uint8Array[] = [];
  const waiters: ((f: Uint8Array | null) => void)[] = [];
  const deliver = (f: Uint8Array | null) => {
    const w = waiters.shift();
    if (w) w(f);
    else if (f) inbox.push(f);
  };
  socket.on("data", (chunk: Uint8Array) => {
    deframer.push(chunk);
    for (let f = deframer.next(); f !== null; f = deframer.next()) deliver(f);
  });
  socket.on("close", () => deliver(null));
  return {
    sendFrame(bytes: Uint8Array) {
      socket.write(frameLengthPrefixed(bytes, MAX_FRAME));
    },
    recvFrame(): Promise<Uint8Array | null> {
      const f = inbox.shift();
      return f ? Promise.resolve(f) : new Promise((res) => waiters.push(res));
    },
  };
}
"#;

/// The channel session body for an Events connection that has a `<->`/`<-` op:
/// handshake, a Codec backed by the op's generated per-type helpers, one outbound
/// event, and the recv loop that heartbeats and dispatches into the generated router.
fn events_session(ch: &ChannelExample) -> String {
    format!(
        r#"
async function session() {{
  const carrier = openTlsCarrier("localhost", 7443);

  // $hello / $hello-ack handshake (control plane). The peer's $hello-ack pins the
  // wire profile for the connection's lifetime.
  await carrier.sendFrame(new Hello([1], ["verbose"], "{service}").encode());
  const ackFrame = await carrier.recvFrame();
  if (ackFrame === null) throw new Error("connection closed during handshake");
  const profile = HelloAck.decode(ackFrame).profile as Profile;

  // The router needs a Codec for this channel's types; back it with the generated
  // per-type helpers (inbound {inbound}, outbound {outbound}).
  const codec: Codec = {{
    decode<T>(bytes: Uint8Array): T {{
      return from{inbound}Cbor(bytes) as T;
    }},
    encode(value: unknown): Uint8Array {{
      return to{outbound}Cbor(value as {outbound});
    }},
  }};

  const handlers: {handlers} = {{
    {method}(msg) {{
      console.log("event {method}", msg);
    }},
  }};

  // Send one outbound event via the generated encoder, framed as a verbose Event.
  const out = {encode}(codec, {{ {sample_field} }} as {outbound});
  await carrier.sendFrame(Event.verbose("{service}", out.method, out.bytes).encode(profile));

  // Recv loop: decode each frame to an Event, answer $ping with $pong, dispatch the
  // rest to the generated router.
  for (let frame = await carrier.recvFrame(); frame !== null; frame = await carrier.recvFrame()) {{
    const ev = Event.decode(frame, profile);
    if (ev.event === control.PING_NAME) {{
      const ping = Heartbeat.decode(ev.payload);
      await carrier.sendFrame(
        Event.verbose("{service}", control.PONG_NAME, new Heartbeat(ping.nonce).encode()).encode(profile),
      );
      continue;
    }}
    {route}(handlers, codec, ev.event!, ev.payload);
  }}
}}

session();
"#,
        service = ch.service_wire,
        inbound = ch.inbound_type,
        outbound = ch.outbound_type,
        handlers = ch.handlers_iface,
        encode = ch.encode_fn,
        route = ch.route_fn,
        method = ch.method,
        sample_field = ch.outbound_sample_field,
    )
}

/// The Events session body when the spec declares no channel ops: the handshake and
/// heartbeat still apply, so they are shown, with a note where the dispatch would go.
const EVENTS_NO_CHANNEL_SESSION_TS: &str = r#"
async function session() {
  const carrier = openTlsCarrier("localhost", 7443);

  // $hello / $hello-ack handshake (control plane).
  await carrier.sendFrame(new Hello([1], ["verbose"]).encode());
  const ackFrame = await carrier.recvFrame();
  if (ackFrame === null) throw new Error("connection closed during handshake");
  const profile = HelloAck.decode(ackFrame).profile as Profile;

  // Recv loop: answer $ping with $pong. This package declares no <->/<- operations,
  // so there is no generated channel router to dispatch typed events into.
  for (let frame = await carrier.recvFrame(); frame !== null; frame = await carrier.recvFrame()) {
    const ev = Event.decode(frame, profile);
    if (ev.event === control.PING_NAME) {
      const ping = Heartbeat.decode(ev.payload);
      await carrier.sendFrame(
        Event.verbose(undefined, control.PONG_NAME, new Heartbeat(ping.nonce).encode()).encode(profile),
      );
    }
  }
}

session();
"#;

/// CSIL-Datagrams over UDP: encode a `->` request with the generated codec, wrap it
/// in a `Datagram`, and `sendDatagram` it fire-and-forget. The recv path
/// `Datagram.decode`s an inbound datagram and decodes its payload with the generated
/// codec — there is NO synchronous response.
fn datagrams_section(pkg: &str, ex: Option<&UnaryExample>) -> String {
    let mut out = String::from("## CSIL-Datagrams (UDP)\n\n");
    out.push_str(
        "Unreliable, unordered, message-oriented. The library owns the `Datagram`\n\
         envelope; you bring a datagram carrier. The UDP carrier below is one example —\n\
         a WebRTC unreliable DataChannel or QUIC datagrams drop in unchanged.\n\n",
    );
    let Some(ex) = ex else {
        out.push_str(
            "This package declares no record `->` operations, so there is no datagram payload to encode.\n\n",
        );
        return out;
    };
    let (Some(req_type), Some(res_type)) = (&ex.req_type, &ex.res_type) else {
        out.push_str(
            "This package's `->` operations have non-record payloads; (de)serialize them manually before framing.\n\n",
        );
        return out;
    };
    out.push_str("```ts\n");
    out.push_str("import { Datagram, type DatagramCarrier } from \"csilgen-transport\";\n");
    out.push_str("import * as dgram from \"node:dgram\";\n");
    out.push_str(&format!(
        "import {{ to{req_type}Cbor, from{res_type}Cbor }} from \"{pkg}\";\n"
    ));
    out.push_str(&format!(
        "import type {{ {req_type}, {res_type} }} from \"{pkg}\";\n\n"
    ));
    out.push_str(DATAGRAMS_CARRIER_TS);
    out.push('\n');
    out.push_str(&format!(
        r#"// The operation's datagram ordinal — its @wire-id, or a channel-agreed number.
const OP_ORD = {op_ord};

async function main() {{
  const carrier = openUdpCarrier("localhost", 9000);

  // Fire-and-forget: encode the `->` request and send it. seq 0 marks an
  // unsequenced datagram.
  const req: {req_type} = {sample};
  await carrier.sendDatagram(new Datagram(OP_ORD, 0, to{req_type}Cbor(req)).encode());

  // Recv path: a datagram of the RESPONSE type MAY arrive later — or never. There is
  // NO synchronous response; the caller must tolerate loss and reordering and handle
  // a reply whenever (if ever) it shows up.
  const inbound = await carrier.recvDatagram();
  if (inbound !== null) {{
    const dg = Datagram.decode(inbound);
    const resp: {res_type} = from{res_type}Cbor(dg.payload);
    console.log("late response", resp);
  }}
}}

main();
"#,
        op_ord = ex.op_ord,
        req_type = req_type,
        res_type = res_type,
        sample = ex.sample,
    ));
    out.push_str("```\n\n");
    out
}

/// The UDP `DatagramCarrier` adapter — spec-independent. `sendDatagram` writes one
/// UDP packet; `recvDatagram` resolves the next inbound packet (or `null`).
const DATAGRAMS_CARRIER_TS: &str = r#"// One example carrier: UDP via node's dgram. Datagrams are unreliable and
// unordered, so the carrier never waits for or correlates a reply.
function openUdpCarrier(host: string, port: number): DatagramCarrier {
  const socket = dgram.createSocket("udp4");
  const inbox: Uint8Array[] = [];
  const waiters: ((d: Uint8Array | null) => void)[] = [];
  socket.on("message", (msg: Uint8Array) => {
    const w = waiters.shift();
    if (w) w(msg);
    else inbox.push(msg);
  });
  return {
    sendDatagram(bytes: Uint8Array) {
      socket.send(bytes, port, host);
    },
    recvDatagram(): Promise<Uint8Array | null> {
      const d = inbox.shift();
      return d ? Promise.resolve(d) : new Promise((res) => waiters.push(res));
    },
  };
}
"#;

/// The pieces a unary (`->`) example call needs: the aggregate field + method to
/// call, a compiling sample request literal, the request/response record type names
/// (so the datagram section can name `to<Req>Cbor`/`from<Res>Cbor`), and the op's
/// datagram ordinal.
struct UnaryExample {
    service_field: String,
    method: String,
    has_request: bool,
    sample: String,
    req_type: Option<String>,
    res_type: Option<String>,
    op_ord: u32,
}

/// The first service (sorted) with a `->` operation the typed client actually emits a
/// method for: a record success, and a record-or-`null` request (matching the
/// client's own gating). `None` for a serviceless package or one whose unary ops are
/// all non-record.
fn first_unary_example(input: &WasmGeneratorInput) -> Option<UnaryExample> {
    let records = codec::record_names(&input.csil_spec);
    for (name, def) in common::sorted_services(&input.csil_spec) {
        for op in &def.operations {
            if !common::is_unidirectional(op) {
                continue;
            }
            let success = common::success_type(&op.output_type);
            let null_input = common::is_null_type(&op.input_type);
            if !codec::is_record_ref(&success, &records)
                || !(null_input || codec::is_record_ref(&op.input_type, &records))
            {
                continue;
            }
            let has_request = !null_input;
            return Some(UnaryExample {
                service_field: common::to_camel(&common::service_base(name)),
                method: common::to_camel(&op.name),
                has_request,
                sample: if has_request {
                    ts_sample(input, &op.input_type)
                } else {
                    String::new()
                },
                req_type: (!null_input).then(|| codec::record_ref_name(&op.input_type)),
                res_type: Some(codec::record_ref_name(&success)),
                // The datagram ordinal is the op's @wire-id when present; otherwise a
                // channel-agreed placeholder the user fills in.
                op_ord: op.wire_id.map(|id| id as u32).unwrap_or(1),
            });
        }
    }
    None
}

/// The pieces the Events session needs: the generated channel router + handler
/// interface + outbound encoder names, the inbound/outbound record type names, the
/// handler method name, a sample field for the outbound literal, and the wire service.
struct ChannelExample {
    service_wire: String,
    route_fn: String,
    handlers_iface: String,
    encode_fn: String,
    method: String,
    inbound_type: String,
    outbound_type: String,
    outbound_sample_field: String,
}

/// The first service (sorted) with a `<->`/`<-` op whose inbound and outbound are both
/// records (so the generated router + encoder + per-type codec helpers exist). `None`
/// when no service has a usable channel op — the Events section then shows the
/// handshake/heartbeat without dispatch wiring.
fn first_channel_example(input: &WasmGeneratorInput) -> Option<ChannelExample> {
    let records = codec::record_names(&input.csil_spec);
    for (name, def) in common::sorted_services(&input.csil_spec) {
        for op in &def.operations {
            if common::is_unidirectional(op) {
                continue;
            }
            // Client-side inbound is the success output; the outbound encoder (only for
            // `<->`) takes the input. Require both to be records for a compiling sample.
            let success = common::success_type(&op.output_type);
            if !codec::is_record_ref(&success, &records)
                || !codec::is_record_ref(&op.input_type, &records)
                || !common::is_bidirectional(op)
            {
                continue;
            }
            let base = common::service_base(name);
            let camel = common::to_camel(&op.name);
            let pascal = {
                let mut c = camel.chars();
                c.next()
                    .map(|f| f.to_uppercase().collect::<String>() + c.as_str())
                    .unwrap_or_default()
            };
            return Some(ChannelExample {
                service_wire: common::service_wire(name),
                route_fn: format!("route{base}Channel"),
                handlers_iface: format!("{base}ChannelHandlers"),
                encode_fn: format!("encode{base}{pascal}"),
                method: camel,
                inbound_type: codec::record_ref_name(&success),
                outbound_type: codec::record_ref_name(&op.input_type),
                outbound_sample_field: channel_sample_field(input, &op.input_type),
            });
        }
    }
    None
}

/// A single `field: <sample>` pair for the outbound record literal in the Events
/// session — the first required field of the outbound record, or empty for a record
/// with no required fields.
fn channel_sample_field(input: &WasmGeneratorInput, ty: &CsilTypeExpression) -> String {
    let CsilTypeExpression::Reference(name) = ty else {
        return String::new();
    };
    let Some(group) = find_record(input, name) else {
        return String::new();
    };
    for e in &group.entries {
        if matches!(e.occurrence, Some(CsilOccurrence::Optional)) {
            continue;
        }
        if let Some(CsilGroupKey::Bare(k)) = &e.key {
            return format!(
                "{}: {}",
                common::to_camel(k),
                ts_sample(input, &e.value_type)
            );
        }
    }
    String::new()
}

/// A compiling TypeScript literal for `ty`: real values for scalars/collections and
/// nested records (required fields only), and an `undefined as any` escape for shapes
/// a generic sample can't fabricate (decimal, choices, tuples) so the snippet always
/// type-checks even if the user must fill those in.
fn ts_sample(input: &WasmGeneratorInput, ty: &CsilTypeExpression) -> String {
    match ty {
        CsilTypeExpression::Builtin(name) => match name.as_str() {
            "text" | "tstr" | "string" => "\"example\"".to_string(),
            "bool" | "boolean" => "false".to_string(),
            "bytes" | "bstr" => "new Uint8Array()".to_string(),
            "timestamp" => "new Date()".to_string(),
            "int" | "uint" | "integer" | "number" | "float" | "float16" | "float32" | "float64"
            | "int8" | "int16" | "int32" | "int64" | "uint8" | "uint16" | "uint32" | "uint64" => {
                "0".to_string()
            }
            _ => "undefined as any".to_string(),
        },
        CsilTypeExpression::Array { .. } => "[]".to_string(),
        CsilTypeExpression::Map { .. } => "{}".to_string(),
        CsilTypeExpression::Reference(name) => match find_record(input, name) {
            Some(group) => record_literal(input, group),
            None => "undefined as any".to_string(),
        },
        _ => "undefined as any".to_string(),
    }
}

/// `{ field: <sample>, ... }` over a record's required fields, keyed by the camelCase
/// names the generated TypeScript types use.
fn record_literal(input: &WasmGeneratorInput, group: &CsilGroupExpression) -> String {
    let fields: Vec<String> = group
        .entries
        .iter()
        .filter(|e| !matches!(e.occurrence, Some(CsilOccurrence::Optional)))
        .filter_map(|e| match &e.key {
            Some(CsilGroupKey::Bare(k)) => Some(format!(
                "{}: {}",
                common::to_camel(k),
                ts_sample(input, &e.value_type)
            )),
            _ => None,
        })
        .collect();
    if fields.is_empty() {
        "{}".to_string()
    } else {
        format!("{{ {} }}", fields.join(", "))
    }
}

/// The record a type reference names, if any. A `Name = { ... }` rule parses as
/// `TypeDef(Group(..))`, while a bare group rule is `GroupDef(..)`; both are records.
fn find_record<'a>(input: &'a WasmGeneratorInput, name: &str) -> Option<&'a CsilGroupExpression> {
    input
        .csil_spec
        .rules
        .iter()
        .filter(|r| r.name == name)
        .find_map(|r| match &r.rule_type {
            CsilRuleType::GroupDef(g) => Some(g),
            CsilRuleType::TypeDef(CsilTypeExpression::Group(g)) => Some(g),
            _ => None,
        })
}

/// The npm package name. An explicit `package_name` wins; otherwise it is derived
/// from the first service's base name (`AuthService` -> `auth-client`), falling
/// back to `csilgen-client` for a service-less spec.
fn package_name(input: &WasmGeneratorInput) -> String {
    if let Some(name) = option_string(input, "package_name") {
        // A leading `@` marks an npm scoped name (`@org/pkg`) whose slash is the scope
        // separator, not a path — keep it whole. Otherwise a path-style `package_name`
        // (e.g. a Go module path) is the cross-ecosystem source of truth and npm wants
        // only its tail. See `package_name_last_segment`.
        if name.starts_with('@') {
            return name;
        }
        return csilgen_common::package_name_last_segment(&name).to_string();
    }
    let services = common::sorted_services(&input.csil_spec);
    if let Some((name, _)) = services.first() {
        let base = common::service_base(name).to_lowercase();
        if !base.is_empty() {
            return format!("{base}-client");
        }
    }
    "csilgen-client".to_string()
}

fn package_version(input: &WasmGeneratorInput) -> String {
    option_string(input, "package_version").unwrap_or_else(|| "0.1.0".to_string())
}

/// A non-empty string option, trimmed. Returns `None` for a missing, blank, or
/// non-string value so callers fall back to their derived default.
fn option_string(input: &WasmGeneratorInput, key: &str) -> Option<String> {
    input
        .config
        .options
        .get(key)
        .and_then(|v| v.as_str())
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_string)
}

fn package_json(input: &WasmGeneratorInput) -> String {
    let name = package_name(input);
    let version = package_version(input);
    let value = serde_json::json!({
        "name": name,
        "version": version,
        // CommonJS: the built `dist/` keeps the widest consumer reach; the `.ts`
        // source specifiers are rewritten to `.js` at build time by
        // `rewriteRelativeImportExtensions` in the shipped tsconfig.
        "type": "commonjs",
        "main": "dist/index.js",
        "types": "dist/index.d.ts",
        "exports": {
            ".": {
                "types": "./dist/index.d.ts",
                "require": "./dist/index.js",
                "default": "./dist/index.js"
            }
        },
        "files": ["dist"],
        "scripts": {
            "build": "tsc"
        },
        "devDependencies": {
            // 5.7 introduced `rewriteRelativeImportExtensions`, which the shipped
            // tsconfig relies on to build the `.ts`-extensioned specifiers.
            "typescript": "^5.7"
        }
    });
    // Pretty-print with a trailing newline so the file reads like a hand-authored one.
    format!("{}\n", serde_json::to_string_pretty(&value).unwrap())
}

/// Strict, declaration-emitting config matching the CommonJS modules the
/// generator writes. `*.ts` picks up the barrel plus every `*.gen.ts`.
/// `rewriteRelativeImportExtensions` (TS 5.7+) is what lets the `.ts`-extensioned
/// source specifiers both typecheck and land as `.js` in the emitted `dist/`.
const TSCONFIG: &str = r#"{
  "compilerOptions": {
    "target": "es2020",
    "module": "commonjs",
    "moduleResolution": "node",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "declaration": true,
    "rewriteRelativeImportExtensions": true,
    "outDir": "dist",
    "lib": ["es2020", "dom"]
  },
  "include": ["*.ts"]
}
"#;

/// Re-export every generated module from a single entry point. Modules are
/// re-exported via `export *` where their names are unique; a module that would
/// reintroduce an already-exported name (client and server both export `Codec`)
/// falls back to an explicit named re-export of only its fresh names, since TS
/// rejects ambiguous star re-exports (TS2308).
fn barrel(input: &WasmGeneratorInput, files: &[GeneratedFile]) -> String {
    let mut out = common::header(input, "index");
    let mut seen: BTreeSet<String> = BTreeSet::new();
    // Already validated by `generate_files`'s eager option check in lib.rs before
    // any file (including this barrel) is emitted.
    let ext = common::import_extension(input).unwrap_or(common::ImportExtension::Ts);
    // Fixed order keeps the barrel deterministic and lets `types`/`codec` claim
    // the shared names before the client/server surfaces do. `stem` is the
    // on-disk filename (always `.ts`, looked up verbatim) minus its extension;
    // `specifier` is what the re-export line actually carries, which follows
    // `import_extension` like every other relative specifier this generator emits.
    for stem in [
        "types.gen",
        "codec.gen",
        "client.gen",
        "client.async.gen",
        "server.gen",
    ] {
        let path = format!("{stem}.ts");
        let specifier = ext.specifier(stem);
        let Some(file) = files.iter().find(|f| f.path == path) else {
            continue;
        };
        let names = exported_names(&file.content);
        if names.iter().any(|n| seen.contains(n)) {
            let mut fresh: Vec<String> = Vec::new();
            for n in &names {
                if !seen.contains(n) && !fresh.contains(n) {
                    fresh.push(n.clone());
                }
            }
            if !fresh.is_empty() {
                out.push_str(&format!(
                    "export {{ {} }} from \"{specifier}\";\n",
                    fresh.join(", ")
                ));
            }
        } else {
            out.push_str(&format!("export * from \"{specifier}\";\n"));
        }
        for n in names {
            seen.insert(n);
        }
    }
    out
}

/// Top-level exported binding names in a generated module. A line-anchored scan
/// (only `export <kw> <name>` at the start of a line) avoids false positives,
/// which matter because a name listed in an explicit re-export must really exist
/// or TS errors; a missed name merely goes un-re-exported.
fn exported_names(content: &str) -> Vec<String> {
    let mut out = Vec::new();
    for line in content.lines() {
        let Some(rest) = line.trim_start().strip_prefix("export ") else {
            continue;
        };
        let rest = rest.strip_prefix("async ").unwrap_or(rest);
        let after = [
            "interface ",
            "type ",
            "class ",
            "function ",
            "const ",
            "enum ",
        ]
        .iter()
        .find_map(|kw| rest.strip_prefix(kw));
        let Some(after) = after else {
            continue;
        };
        let name: String = after
            .chars()
            .take_while(|c| c.is_alphanumeric() || *c == '_' || *c == '$')
            .collect();
        if !name.is_empty() {
            out.push(name);
        }
    }
    out
}
