//! Self-contained, publishable npm-package emission.
//!
//! When `emit_packages` includes `"typescript"`, the generator turns the output
//! directory into a buildable npm package: a barrel `index.ts`, a `package.json`,
//! and a `tsconfig.json`. The package is CommonJS because the generated `.gen.ts`
//! modules import each other with extension-less relative specifiers
//! (`./types.gen`), which only resolve under `node`-style module resolution; an
//! ESM (`nodenext`) package would require `.js` suffixes the emitters do not
//! write.

use crate::common;
use csilgen_common::{
    CsilGroupExpression, CsilGroupKey, CsilOccurrence, CsilRuleType, CsilTypeExpression,
    GeneratedFile, WasmGeneratorInput,
};
use std::collections::BTreeSet;

/// Whether the consumer asked for a TypeScript package. The option is a JSON
/// array of target ids; a lone string is accepted too so a hand-written config
/// (`"emit_packages": "typescript"`) still works. Anything else means "no".
pub fn wants_typescript_package(input: &WasmGeneratorInput) -> bool {
    match input.config.options.get("emit_packages") {
        Some(serde_json::Value::Array(items)) => {
            items.iter().any(|v| v.as_str() == Some("typescript"))
        }
        Some(serde_json::Value::String(s)) => s == "typescript",
        _ => false,
    }
}

/// Append the package scaffolding (barrel + `package.json` + `tsconfig.json`) to
/// the already-generated module files. A no-op unless `emit_packages` opts in.
pub fn augment(input: &WasmGeneratorInput, files: &mut Vec<GeneratedFile>) {
    if !wants_typescript_package(input) {
        return;
    }

    let barrel = barrel(input, files);
    files.push(GeneratedFile {
        path: "index.ts".to_string(),
        content: barrel,
    });
    files.push(GeneratedFile {
        path: "package.json".to_string(),
        content: package_json(input),
    });
    files.push(GeneratedFile {
        path: "tsconfig.json".to_string(),
        content: TSCONFIG.to_string(),
    });
    // The README is the one piece a consumer can opt out of: only an explicit
    // `emit_readme: false` suppresses it, so a missing or non-bool value (and `true`)
    // leaves the default-on behavior untouched.
    if wants_readme(input) {
        files.push(GeneratedFile {
            path: "README.md".to_string(),
            content: readme(input),
        });
    }
}

/// Whether to emit the package `README.md`. Default true; only an explicit
/// `emit_readme: false` suppresses it.
fn wants_readme(input: &WasmGeneratorInput) -> bool {
    input
        .config
        .options
        .get("emit_readme")
        .and_then(|v| v.as_bool())
        != Some(false)
}

/// The package README, with a copy-paste **Quickstart**. For a client package the
/// Quickstart is a complete, dependency-free CSIL-RPC carrier (it reuses this
/// package's own generated CBOR codec for the envelope, so it adds no third-party
/// dependency), the typed client constructed over it, and one example call — a user
/// changes only the base-URL string. A serviceless (types-only) package gets the
/// consume-the-package section without a carrier.
fn readme(input: &WasmGeneratorInput) -> String {
    let name = package_name(input);
    let mut out = format!(
        "# {name}\n\n\
         Generated by csilgen. A typed, transport-agnostic CSIL-RPC client: the\n\
         generated codec owns CBOR (de)serialization; you supply a *carrier* that only\n\
         moves bytes.\n\n\
         ## Install\n\n\
         ```sh\n\
         npm install {name}\n\
         ```\n\n"
    );

    match first_unary_example(input) {
        Some(example) => out.push_str(&quickstart(input, &name, &example)),
        None => {
            out.push_str(&format!(
                "## Quickstart\n\n\
                 This package has no service operations — import its generated types and\n\
                 codec directly:\n\n\
                 ```ts\n\
                 import type {{ /* your types */ }} from \"{name}\";\n```\n"
            ));
        }
    }
    out
}

/// The client Quickstart: a dependency-free async CSIL-RPC carrier (browsers and
/// async runtimes need an async carrier — `fetch` is async — so it implements the
/// generated `AsyncServiceTransport` and the async client), then the typed call.
fn quickstart(input: &WasmGeneratorInput, pkg: &str, ex: &UnaryExample) -> String {
    let configured =
        option_string(input, "aggregate_class_name").unwrap_or_else(|| "ApiClient".to_string());
    let aggregate = format!("Async{configured}");
    // Imports: the async client + transport type, plus exactly the generic codec
    // helpers the carrier uses to build/parse the CSIL-RPC envelope.
    let mut out = String::from("## Quickstart\n\n");
    out.push_str(
        "A complete CSIL-RPC carrier (no third-party deps — it reuses this package's\n\
         generated CBOR codec for the envelope) plus the typed client. Change the one\n\
         base-URL string.\n\n",
    );
    out.push_str("```ts\n");
    out.push_str(&format!(
        "import {{\n  {aggregate},\n  type AsyncServiceTransport,\n  encodeValue,\n  decode,\n  mapGet,\n  requireKey,\n  asNumber,\n  asString,\n  asBytes,\n  type CborValue,\n}} from \"{pkg}\";\n\n"
    ));
    out.push_str(CARRIER_TS);
    out.push('\n');
    // The example call: construct the aggregate over the carrier, call the first op.
    out.push_str(&format!(
        "async function main() {{\n  \
         const client = new {aggregate}(new CsilRpcTransport(\"http://localhost:5080\"));\n  "
    ));
    if ex.has_request {
        out.push_str(&format!(
            "const resp = await client.{}.{}({});\n  ",
            ex.service_field, ex.method, ex.sample
        ));
    } else {
        out.push_str(&format!(
            "const resp = await client.{}.{}();\n  ",
            ex.service_field, ex.method
        ));
    }
    out.push_str("console.log(resp);\n}\n\nmain();\n");
    out.push_str("```\n");
    out
}

/// The carrier body — identical for every spec, so it is a constant. It wraps the
/// already-encoded request in a `CsilRpcRequest` envelope (tag-24 payload), POSTs it
/// to `{baseUrl}/csil/v1/rpc`, and returns the response payload bytes for the
/// generated client to decode. A non-zero transport `status` or a typed
/// `ServiceError` arm is surfaced as a thrown error.
const CARRIER_TS: &str = r#"// The carrier owns only the CSIL-RPC envelope + HTTP; it never touches your types.
class CsilRpcTransport implements AsyncServiceTransport {
  constructor(private readonly baseUrl: string) {}

  async call(service: string, op: string, req: Uint8Array): Promise<Uint8Array> {
    // CsilRpcRequest = { v, service, op, payload: #6.24(bstr) }. Keys are inserted
    // in canonical (length-then-bytewise) order; the payload is the encoded request
    // wrapped in tag 24 (embedded CBOR).
    const envelope: CborValue = new Map<CborValue, CborValue>([
      ["v", 1],
      ["op", op],
      ["service", service],
      ["payload", { tag: 24, value: req }],
    ]);
    const http = await fetch(this.baseUrl.replace(/\/+$/, "") + "/csil/v1/rpc", {
      method: "POST",
      headers: { "Content-Type": "application/cbor", Accept: "application/cbor" },
      // `Uint8Array` is a valid fetch body at runtime; the cast satisfies the DOM
      // typings, whose `BodyInit` predates TS's generic `Uint8Array<ArrayBufferLike>`.
      body: encodeValue(envelope) as BodyInit,
    });
    if (!http.ok) throw new Error(`csil-rpc ${service}/${op}: http ${http.status}`);

    const env = decode(new Uint8Array(await http.arrayBuffer()));
    const status = asNumber(requireKey(env, "status"));
    if (status !== 0) throw new Error(`csil-rpc ${service}/${op}: transport status ${status}`);

    const payload = requireKey(env, "payload");
    if (typeof payload !== "object" || payload === null || !("tag" in payload) || payload.tag !== 24) {
      throw new Error("csil-rpc: response payload is not a tag-24 byte string");
    }
    const inner = asBytes((payload as { value: CborValue }).value);

    // A typed `ServiceError` arm (variant "ServiceError") is an application error,
    // distinct from a transport failure.
    const variant = mapGet(env, "variant");
    if (variant !== undefined && asString(variant) === "ServiceError") {
      const e = decode(inner);
      throw new Error(
        `service error ${asNumber(requireKey(e, "code"))}: ${asString(requireKey(e, "message"))}`,
      );
    }
    return inner;
  }
}
"#;

/// The pieces the Quickstart's example call needs: which aggregate field + method to
/// call and a compiling sample request literal (empty when the op takes no request).
struct UnaryExample {
    service_field: String,
    method: String,
    has_request: bool,
    sample: String,
}

/// The first service (in sorted order) that has a `->` operation, reduced to an
/// example call. `None` for a serviceless / types-only package.
fn first_unary_example(input: &WasmGeneratorInput) -> Option<UnaryExample> {
    for (name, def) in common::sorted_services(&input.csil_spec) {
        if let Some(op) = def
            .operations
            .iter()
            .find(|op| common::is_unidirectional(op))
        {
            let has_request = !common::is_null_type(&op.input_type);
            return Some(UnaryExample {
                service_field: common::to_camel(&common::service_base(name)),
                method: common::to_camel(&op.name),
                has_request,
                sample: if has_request {
                    ts_sample(input, &op.input_type)
                } else {
                    String::new()
                },
            });
        }
    }
    None
}

/// A compiling TypeScript literal for `ty`: real values for scalars/collections and
/// nested records (required fields only), and an `undefined as any` escape for shapes
/// a generic sample can't fabricate (decimal, choices, tuples) so the snippet always
/// type-checks even if the user must fill those in.
fn ts_sample(input: &WasmGeneratorInput, ty: &CsilTypeExpression) -> String {
    match ty {
        CsilTypeExpression::Builtin(name) => match name.as_str() {
            "text" | "tstr" | "string" => "\"example\"".to_string(),
            "bool" | "boolean" => "false".to_string(),
            "bytes" | "bstr" => "new Uint8Array()".to_string(),
            "timestamp" => "new Date()".to_string(),
            "int" | "uint" | "integer" | "number" | "float" | "float16" | "float32" | "float64"
            | "int8" | "int16" | "int32" | "int64" | "uint8" | "uint16" | "uint32" | "uint64" => {
                "0".to_string()
            }
            _ => "undefined as any".to_string(),
        },
        CsilTypeExpression::Array { .. } => "[]".to_string(),
        CsilTypeExpression::Map { .. } => "{}".to_string(),
        CsilTypeExpression::Reference(name) => match find_record(input, name) {
            Some(group) => record_literal(input, group),
            None => "undefined as any".to_string(),
        },
        _ => "undefined as any".to_string(),
    }
}

/// `{ field: <sample>, ... }` over a record's required fields, keyed by the camelCase
/// names the generated TypeScript types use.
fn record_literal(input: &WasmGeneratorInput, group: &CsilGroupExpression) -> String {
    let fields: Vec<String> = group
        .entries
        .iter()
        .filter(|e| !matches!(e.occurrence, Some(CsilOccurrence::Optional)))
        .filter_map(|e| match &e.key {
            Some(CsilGroupKey::Bare(k)) => Some(format!(
                "{}: {}",
                common::to_camel(k),
                ts_sample(input, &e.value_type)
            )),
            _ => None,
        })
        .collect();
    if fields.is_empty() {
        "{}".to_string()
    } else {
        format!("{{ {} }}", fields.join(", "))
    }
}

/// The record a type reference names, if any. A `Name = { ... }` rule parses as
/// `TypeDef(Group(..))`, while a bare group rule is `GroupDef(..)`; both are records.
fn find_record<'a>(input: &'a WasmGeneratorInput, name: &str) -> Option<&'a CsilGroupExpression> {
    input
        .csil_spec
        .rules
        .iter()
        .filter(|r| r.name == name)
        .find_map(|r| match &r.rule_type {
            CsilRuleType::GroupDef(g) => Some(g),
            CsilRuleType::TypeDef(CsilTypeExpression::Group(g)) => Some(g),
            _ => None,
        })
}

/// The npm package name. An explicit `package_name` wins; otherwise it is derived
/// from the first service's base name (`AuthService` -> `auth-client`), falling
/// back to `csilgen-client` for a service-less spec.
fn package_name(input: &WasmGeneratorInput) -> String {
    if let Some(name) = option_string(input, "package_name") {
        return name;
    }
    let services = common::sorted_services(&input.csil_spec);
    if let Some((name, _)) = services.first() {
        let base = common::service_base(name).to_lowercase();
        if !base.is_empty() {
            return format!("{base}-client");
        }
    }
    "csilgen-client".to_string()
}

fn package_version(input: &WasmGeneratorInput) -> String {
    option_string(input, "package_version").unwrap_or_else(|| "0.1.0".to_string())
}

/// A non-empty string option, trimmed. Returns `None` for a missing, blank, or
/// non-string value so callers fall back to their derived default.
fn option_string(input: &WasmGeneratorInput, key: &str) -> Option<String> {
    input
        .config
        .options
        .get(key)
        .and_then(|v| v.as_str())
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_string)
}

fn package_json(input: &WasmGeneratorInput) -> String {
    let name = package_name(input);
    let version = package_version(input);
    let value = serde_json::json!({
        "name": name,
        "version": version,
        // CommonJS: the emitted modules use extension-less relative imports, which
        // require `node` module resolution rather than ESM.
        "type": "commonjs",
        "main": "dist/index.js",
        "types": "dist/index.d.ts",
        "exports": {
            ".": {
                "types": "./dist/index.d.ts",
                "require": "./dist/index.js",
                "default": "./dist/index.js"
            }
        },
        "files": ["dist"],
        "scripts": {
            "build": "tsc"
        },
        "devDependencies": {
            "typescript": "^5"
        }
    });
    // Pretty-print with a trailing newline so the file reads like a hand-authored one.
    format!("{}\n", serde_json::to_string_pretty(&value).unwrap())
}

/// Strict, declaration-emitting config matching the CommonJS modules the
/// generator writes. `*.ts` picks up the barrel plus every `*.gen.ts`.
const TSCONFIG: &str = r#"{
  "compilerOptions": {
    "target": "es2020",
    "module": "commonjs",
    "moduleResolution": "node",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "declaration": true,
    "outDir": "dist",
    "lib": ["es2020", "dom"]
  },
  "include": ["*.ts"]
}
"#;

/// Re-export every generated module from a single entry point. Modules are
/// re-exported via `export *` where their names are unique; a module that would
/// reintroduce an already-exported name (client and server both export `Codec`)
/// falls back to an explicit named re-export of only its fresh names, since TS
/// rejects ambiguous star re-exports (TS2308).
fn barrel(input: &WasmGeneratorInput, files: &[GeneratedFile]) -> String {
    let mut out = common::header(input, "index");
    let mut seen: BTreeSet<String> = BTreeSet::new();
    // Fixed order keeps the barrel deterministic and lets `types`/`codec` claim
    // the shared names before the client/server surfaces do.
    for path in [
        "types.gen.ts",
        "codec.gen.ts",
        "client.gen.ts",
        "client.async.gen.ts",
        "server.gen.ts",
    ] {
        let Some(file) = files.iter().find(|f| f.path == path) else {
            continue;
        };
        let stem = path.strip_suffix(".ts").unwrap_or(path);
        let names = exported_names(&file.content);
        if names.iter().any(|n| seen.contains(n)) {
            let mut fresh: Vec<String> = Vec::new();
            for n in &names {
                if !seen.contains(n) && !fresh.contains(n) {
                    fresh.push(n.clone());
                }
            }
            if !fresh.is_empty() {
                out.push_str(&format!(
                    "export {{ {} }} from \"./{stem}\";\n",
                    fresh.join(", ")
                ));
            }
        } else {
            out.push_str(&format!("export * from \"./{stem}\";\n"));
        }
        for n in names {
            seen.insert(n);
        }
    }
    out
}

/// Top-level exported binding names in a generated module. A line-anchored scan
/// (only `export <kw> <name>` at the start of a line) avoids false positives,
/// which matter because a name listed in an explicit re-export must really exist
/// or TS errors; a missed name merely goes un-re-exported.
fn exported_names(content: &str) -> Vec<String> {
    let mut out = Vec::new();
    for line in content.lines() {
        let Some(rest) = line.trim_start().strip_prefix("export ") else {
            continue;
        };
        let rest = rest.strip_prefix("async ").unwrap_or(rest);
        let after = [
            "interface ",
            "type ",
            "class ",
            "function ",
            "const ",
            "enum ",
        ]
        .iter()
        .find_map(|kw| rest.strip_prefix(kw));
        let Some(after) = after else {
            continue;
        };
        let name: String = after
            .chars()
            .take_while(|c| c.is_alphanumeric() || *c == '_' || *c == '$')
            .collect();
        if !name.is_empty() {
            out.push(name);
        }
    }
    out
}
