#!/usr/bin/env python3
"""Generate tests/vectors.gen.h from the language-neutral conformance vectors.

The C conformance test consumes the byte-exact fixtures in
transports/conformance/{rpc,events,datagrams}.json without taking a runtime JSON
dependency: this script flattens each vector's `input` (and decoded `hex`) into a
static C array the test iterates. Run it only when the vectors change; the output
is checked in so the CMake build needs no Python.

Usage:
    tools/gen_vectors.py <conformance_dir> <output_header>
"""
import json
import sys
from pathlib import Path


def c_bytes(name, hexstr):
    """Emit a `static const uint8_t <name>[]` for hex (or nothing when empty)."""
    if hexstr is None or hexstr == "":
        return "", "NULL", "0"
    data = bytes.fromhex(hexstr)
    body = ", ".join(f"0x{b:02x}" for b in data)
    decl = f"static const uint8_t {name}[] = {{{body}}};"
    return decl, name, str(len(data))


def cstr(s):
    if s is None:
        return "NULL"
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def opt_u64(field):
    """(has, value) for an optional unsigned integer that may be JSON null."""
    if field is None:
        return "false", "0"
    return "true", str(int(field))


def main():
    conf_dir = Path(sys.argv[1])
    out_path = Path(sys.argv[2])
    lines = []
    decls = []

    def add(line):
        lines.append(line)

    add("/* Generated by tools/gen_vectors.py from the conformance JSON fixtures. */")
    add("/* DO NOT EDIT. Regenerate when the conformance vectors change. */")
    add("#ifndef CSIL_TEST_VECTORS_GEN_H")
    add("#define CSIL_TEST_VECTORS_GEN_H")
    add("")
    add("#include <stddef.h>")
    add("#include <stdint.h>")
    add("#include <stdbool.h>")
    add("")

    # ---- RPC ----
    add("typedef struct {")
    add("    const char *name;")
    add("    const uint8_t *hex; size_t hex_len;")
    add("    const char *kind;")
    add("    const char *service;")
    add("    const char *op;")
    add("    const char *event;")
    add("    bool has_id; uint64_t id;")
    add("    const char *auth;")
    add("    bool has_status; int64_t status;")
    add("    const char *variant;")
    add("    const char *error;")
    add("    const uint8_t *payload; size_t payload_len;")
    add("} rpc_vector;")
    add("")
    rpc = json.loads((conf_dir / "rpc.json").read_text())["vectors"]
    rpc_rows = []
    for i, v in enumerate(rpc):
        inp = v["input"]
        hdecl, hptr, hlen = c_bytes(f"rpc_hex_{i}", v["hex"])
        pdecl, pptr, plen = c_bytes(f"rpc_pay_{i}", inp.get("payload_hex"))
        decls.append(hdecl)
        if pdecl:
            decls.append(pdecl)
        has_id, idv = opt_u64(inp.get("id"))
        status = inp.get("status")
        has_status = "true" if status is not None else "false"
        statusv = str(int(status)) if status is not None else "0"
        rpc_rows.append(
            "    {"
            f"{cstr(v['name'])}, {hptr}, {hlen}, {cstr(inp.get('kind'))}, "
            f"{cstr(inp.get('service'))}, {cstr(inp.get('op'))}, {cstr(inp.get('event'))}, "
            f"{has_id}, {idv}, {cstr(inp.get('auth'))}, {has_status}, {statusv}, "
            f"{cstr(inp.get('variant'))}, {cstr(inp.get('error'))}, {pptr}, {plen}"
            "}"
        )

    # ---- Events ----
    add("typedef struct {")
    add("    const char *name;")
    add("    const uint8_t *hex; size_t hex_len;")
    add("    const char *control;")
    add("    const char *profile;")
    add("    const char *service;")
    add("    const char *event;")
    add("    bool has_service_ord; uint64_t service_ord;")
    add("    bool has_op_ord; uint64_t op_ord;")
    add("    bool has_id; uint64_t id;")
    add("    const uint8_t *payload; size_t payload_len;")
    add("    const uint64_t *versions; size_t versions_len;")
    add("    const char *const *profiles; size_t profiles_len;")
    add("    const char *auth;")
    add("    bool has_v; uint64_t v;")
    add("    const char *session;")
    add("    bool has_nonce; uint64_t nonce;")
    add("    bool has_at; uint64_t at;")
    add("    const char *reason;")
    add("    bool has_status; int64_t status;")
    add("} events_vector;")
    add("")
    events = json.loads((conf_dir / "events.json").read_text())["vectors"]
    ev_rows = []
    for i, v in enumerate(events):
        inp = v["input"]
        hdecl, hptr, hlen = c_bytes(f"ev_hex_{i}", v["hex"])
        decls.append(hdecl)
        pdecl, pptr, plen = c_bytes(f"ev_pay_{i}", inp.get("payload_hex"))
        if pdecl:
            decls.append(pdecl)
        versions = inp.get("versions")
        vers_ptr, vers_len = "NULL", "0"
        if versions:
            decls.append(
                f"static const uint64_t ev_vers_{i}[] = {{"
                + ", ".join(str(int(x)) for x in versions)
                + "};"
            )
            vers_ptr, vers_len = f"ev_vers_{i}", str(len(versions))
        profiles = inp.get("profiles")
        prof_ptr, prof_len = "NULL", "0"
        if profiles:
            decls.append(
                f"static const char *const ev_profs_{i}[] = {{"
                + ", ".join(cstr(x) for x in profiles)
                + "};"
            )
            prof_ptr, prof_len = f"ev_profs_{i}", str(len(profiles))
        has_sord, sord = opt_u64(inp.get("service_ord"))
        has_oord, oord = opt_u64(inp.get("op_ord"))
        has_id, idv = opt_u64(inp.get("id"))
        has_v, vv = opt_u64(inp.get("v"))
        has_nonce, noncev = opt_u64(inp.get("nonce"))
        has_at, atv = opt_u64(inp.get("at"))
        status = inp.get("status")
        has_status = "true" if status is not None else "false"
        statusv = str(int(status)) if status is not None else "0"
        ev_rows.append(
            "    {"
            f"{cstr(v['name'])}, {hptr}, {hlen}, {cstr(inp.get('control'))}, "
            f"{cstr(inp.get('profile'))}, {cstr(inp.get('service'))}, {cstr(inp.get('event'))}, "
            f"{has_sord}, {sord}, {has_oord}, {oord}, {has_id}, {idv}, {pptr}, {plen}, "
            f"{vers_ptr}, {vers_len}, {prof_ptr}, {prof_len}, {cstr(inp.get('auth'))}, "
            f"{has_v}, {vv}, {cstr(inp.get('session'))}, {has_nonce}, {noncev}, "
            f"{has_at}, {atv}, {cstr(inp.get('reason'))}, {has_status}, {statusv}"
            "}"
        )

    # ---- Datagrams ----
    add("typedef struct {")
    add("    const char *name;")
    add("    const uint8_t *hex; size_t hex_len;")
    add("    const char *profile;")
    add("    bool has_op_ord; uint64_t op_ord;")
    add("    bool has_seq; uint64_t seq;")
    add("    bool has_epoch; uint64_t epoch;")
    add("    const uint8_t *payload; size_t payload_len;")
    add("    const uint8_t *body; size_t body_len;")
    add("} datagram_vector;")
    add("")
    dgrams = json.loads((conf_dir / "datagrams.json").read_text())["vectors"]
    dg_rows = []
    for i, v in enumerate(dgrams):
        inp = v["input"]
        hdecl, hptr, hlen = c_bytes(f"dg_hex_{i}", v["hex"])
        decls.append(hdecl)
        pdecl, pptr, plen = c_bytes(f"dg_pay_{i}", inp.get("payload_hex"))
        if pdecl:
            decls.append(pdecl)
        bdecl, bptr, blen = c_bytes(f"dg_body_{i}", inp.get("body_hex"))
        if bdecl:
            decls.append(bdecl)
        has_oord, oord = opt_u64(inp.get("op_ord"))
        has_seq, seqv = opt_u64(inp.get("seq"))
        has_epoch, epochv = opt_u64(inp.get("epoch"))
        dg_rows.append(
            "    {"
            f"{cstr(v['name'])}, {hptr}, {hlen}, {cstr(inp.get('profile'))}, "
            f"{has_oord}, {oord}, {has_seq}, {seqv}, {has_epoch}, {epochv}, "
            f"{pptr}, {plen}, {bptr}, {blen}"
            "}"
        )

    out = []
    out.append("\n".join(lines))
    out.append("\n".join(d for d in decls if d))
    out.append("")
    out.append("static const rpc_vector RPC_VECTORS[] = {")
    out.append(",\n".join(rpc_rows))
    out.append("};")
    out.append(f"static const size_t RPC_VECTOR_COUNT = {len(rpc_rows)};")
    out.append("")
    out.append("static const events_vector EVENTS_VECTORS[] = {")
    out.append(",\n".join(ev_rows))
    out.append("};")
    out.append(f"static const size_t EVENTS_VECTOR_COUNT = {len(ev_rows)};")
    out.append("")
    out.append("static const datagram_vector DATAGRAM_VECTORS[] = {")
    out.append(",\n".join(dg_rows))
    out.append("};")
    out.append(f"static const size_t DATAGRAM_VECTOR_COUNT = {len(dg_rows)};")
    out.append("")
    out.append("#endif /* CSIL_TEST_VECTORS_GEN_H */")
    out.append("")

    out_path.write_text("\n".join(out))
    print(f"wrote {out_path} "
          f"({len(rpc_rows)} rpc, {len(ev_rows)} events, {len(dg_rows)} datagrams)")


if __name__ == "__main__":
    main()
